// @ts-nocheck
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Zone = "red" | "yellow" | "normal";
type View = "overview" | "actions" | "problems" | "slices" | "comments" | "questions" | "surveys";
type Survey = { id: string; title: string; description?: string | null; status: "draft" | "active" | "closed"; createdAt: string; stats: { started: number; completed: number }; questionCount: number };
type Question = { id: string; surveyId: string; position: number; code: string; text: string; category: string; type: "scale_1_5" | "single_choice" | "multi_choice" | "text"; options: string[]; required: boolean; maxChoices: number | null };
type Campaign = { id: string; title: string; status: string; total: number; sent: number; failed: number; createdAt: string; finishedAt: string | null };
type SurveyData = { surveys: Survey[]; activeSurvey: { id: string } | null; selectedSurveyId?: string; diagnostics?: { defaultSurveyCreated: boolean; activeSurveyId: string | null; activeQuestionCount: number; surveyHashSaltConfigured: boolean; knownBotUsers?: number }; analytics: any | null; campaigns?: Campaign[] };

const LABELS: Record<string, string> = { clarity: "Понятность задач", working_conditions: "Условия", staffing: "Люди в смене", workload: "Нагрузка", fairness: "Справедливость", schedule: "График", team: "Коллектив", manager: "Руководитель", training: "Обучение", onboarding: "Адаптация", rules: "Правила", communication: "Коммуникация", office_store: "Офис и магазины", compensation: "Зарплата", recognition: "Признание", growth: "Развитие", safety: "Безопасность", trust: "Доверие", satisfaction: "Удовлетворённость", custom: "Другое" };
const CATEGORIES = Object.entries(LABELS).map(([value, label]) => ({ value, label }));
const TYPE_LABELS: Record<string, string> = { scale_1_5: "Шкала 1-5", single_choice: "Один вариант", multi_choice: "Несколько вариантов", text: "Текст" };
const BRANCHES = [{ value: "all", label: "Всем" }, { value: "store", label: "Магазин" }, { value: "office", label: "Офис" }, { value: "warehouse", label: "Склад" }];

async function api<T>(url: string, init?: RequestInit): Promise<T> {
  const r = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const d = await r.json() as T & { error?: string };
  if (!r.ok) throw new Error(d.error ?? "Ошибка запроса");
  return d;
}

function cleanTitle(title: string) { return title.replace(/^Копия:\s*/i, ""); }
function statusLabel(status: Survey["status"]) { return status === "active" ? "Текущий опрос" : status === "draft" ? "Черновик" : "Завершён"; }
function statusClass(status: Survey["status"]) { return status === "active" ? "bg-emerald-100 text-emerald-800" : status === "draft" ? "bg-sky-100 text-sky-800" : "bg-zinc-100 text-zinc-700"; }
function campaignStatus(status: string) { return status === "sending" ? "Отправляется" : status === "finished" ? "Отправлено" : status === "failed" ? "Ошибка" : "Черновик"; }
function zoneForProblem(share: number): Zone { return share >= 30 ? "red" : share >= 15 ? "yellow" : "normal"; }
function riskZone(value?: number): Zone { if (value === undefined) return "normal"; if (value >= 60) return "red"; if (value >= 35) return "yellow"; return "normal"; }
function scoreZone(value: number | null): Zone { if (value === null) return "normal"; if (value < 3.2) return "red"; if (value <= 3.8) return "yellow"; return "normal"; }
function zoneClass(zone: Zone) { return zone === "red" ? "border-red-200 bg-red-50 text-red-900" : zone === "yellow" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-900"; }
function barClass(zone: Zone) { return zone === "red" ? "bg-red-500" : zone === "yellow" ? "bg-amber-500" : "bg-emerald-500"; }
function zt(zone: Zone) { return zone === "red" ? "красная" : zone === "yellow" ? "жёлтая" : "норма"; }
function clamp(value: number) { return Math.max(0, Math.min(100, value)); }
function reliabilityText(value: string) { return value === "good" ? "можно анализировать" : value === "medium" ? "осторожно" : "мало данных"; }
function branchOf(code: string) { if (code.startsWith("store_")) return "store"; if (code.startsWith("office_")) return "office"; if (code.startsWith("warehouse_")) return "warehouse"; return "all"; }
function stripBranch(code: string) { return code.replace(/^(store_|office_|warehouse_)/, ""); }
function withBranch(code: string, branch: string) { const base = stripBranch(code || `q_${Math.random().toString(36).slice(2, 8)}`).replace(/[^a-zA-Z0-9_]/g, "_"); return branch === "store" ? `store_${base}` : branch === "office" ? `office_${base}` : branch === "warehouse" ? `warehouse_${base}` : base; }

function Kpi({ title, value, hint, zone = "normal" }: { title: string; value: string | number; hint: string; zone?: Zone }) {
  return <div className={`rounded-3xl border p-5 shadow-sm ${zoneClass(zone)}`}><p className="text-xs font-semibold uppercase tracking-[0.16em] opacity-70">{title}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-sm leading-5 opacity-80">{hint}</p></div>;
}
function Pill({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${className}`}>{children}</span>; }
function StatusPill({ ok, label }: { ok: boolean; label: string }) { return <Pill className={ok ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}>{ok ? "✓" : "!"} {label}</Pill>; }
function BarRows({ items, type }: { items: Array<any>; type: "category" | "problem" }) {
  if (!items.length) return <p className="rounded-2xl bg-zinc-50 p-5 text-sm text-zinc-500">Пока нет данных.</p>;
  return <div className="space-y-4">{items.map((item) => { const zone = type === "category" ? item.zone : item.zone ?? zoneForProblem(item.share); const width = type === "category" ? clamp((item.average / 5) * 100) : clamp(item.share); return <div key={`${item.category ?? item.option}-${item.question ?? ""}`}><div className="mb-1 flex items-center justify-between gap-3 text-sm"><span className="font-medium">{item.label ?? LABELS[item.category] ?? item.option}</span><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${zoneClass(zone)}`}>{type === "category" ? item.average : `${item.share}%`}</span></div><div className="h-3 overflow-hidden rounded-full bg-zinc-100"><div className={`h-full rounded-full ${barClass(zone)}`} style={{ width: `${width}%` }} /></div><p className="mt-1 text-xs text-zinc-500">{zt(zone)} · {item.count} {type === "category" ? "ответов" : "выборов"}</p></div>; })}</div>;
}
function RiskDonut({ red, yellow, normal }: { red: number; yellow: number; normal: number }) { const total = Math.max(1, red + yellow + normal); const redPart = (red / total) * 100; const yellowPart = ((red + yellow) / total) * 100; return <div className="flex items-center gap-5"><div className="grid h-36 w-36 place-items-center rounded-full" style={{ background: `conic-gradient(#ef4444 0 ${redPart}%, #f59e0b ${redPart}% ${yellowPart}%, #22c55e ${yellowPart}% 100%)` }}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><span className="text-2xl font-semibold">{red + yellow}</span><span className="-mt-4 text-xs text-zinc-500">зон риска</span></div></div><div className="space-y-2 text-sm"><p><span className="mr-2 inline-block h-3 w-3 rounded-full bg-red-500" />Красные: {red}</p><p><span className="mr-2 inline-block h-3 w-3 rounded-full bg-amber-500" />Жёлтые: {yellow}</p><p><span className="mr-2 inline-block h-3 w-3 rounded-full bg-emerald-500" />Норма: {normal}</p></div></div>; }

function emptyQuestion(surveyId: string): Question { return { id: "", surveyId, position: 1, code: `q_${Math.random().toString(36).slice(2, 8)}`, text: "", category: "custom", type: "scale_1_5", options: [], required: true, maxChoices: 3 }; }

function QuestionEditor({ surveyId }: { surveyId: string }) {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [draft, setDraft] = useState<Question>(() => emptyQuestion(surveyId));
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { const data = await api<{ questions: Question[] }>(`/api/admin/surveys/questions?surveyId=${encodeURIComponent(surveyId)}`); setQuestions(data.questions); setDraft((prev) => ({ ...emptyQuestion(surveyId), position: data.questions.length + 1, code: prev.id ? prev.code : `q_${data.questions.length + 1}` })); }, [surveyId]);
  useEffect(() => { void load(); }, [load]);
  async function saveQuestion(question: Question, create = false) { const payload = { ...question, code: withBranch(question.code, branchOf(question.code)), options: question.options.join("\n") }; await api("/api/admin/surveys/questions", { method: create ? "POST" : "PATCH", body: JSON.stringify(payload) }); setMessage(create ? "Вопрос добавлен" : "Вопрос сохранён"); await load(); }
  async function remove(id: string) { if (!confirm("Удалить вопрос? Ответы по нему пропадут из детализации отчёта.")) return; await api(`/api/admin/surveys/questions?id=${encodeURIComponent(id)}`, { method: "DELETE" }); setMessage("Вопрос удалён"); await load(); }
  function renderForm(q: Question, setQ: (q: Question) => void, create = false) { const branch = branchOf(q.code); return <div className="grid gap-3 rounded-3xl border border-zinc-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-[80px_160px_160px_160px_1fr]"><input className="field" type="number" value={q.position} onChange={(e) => setQ({ ...q, position: Number(e.target.value) || 1 })} /><select className="field" value={q.type} onChange={(e) => setQ({ ...q, type: e.target.value as Question["type"] })}>{Object.entries(TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="field" value={q.category} onChange={(e) => setQ({ ...q, category: e.target.value })}>{CATEGORIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select className="field" value={branch} onChange={(e) => setQ({ ...q, code: withBranch(q.code, e.target.value) })}>{BRANCHES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input className="field" value={stripBranch(q.code)} onChange={(e) => setQ({ ...q, code: withBranch(e.target.value, branch) })} placeholder="код вопроса" /></div><textarea className="field min-h-20" value={q.text} onChange={(e) => setQ({ ...q, text: e.target.value })} placeholder="Текст вопроса" />{(q.type === "single_choice" || q.type === "multi_choice") && <textarea className="field min-h-24" value={q.options.join("\n")} onChange={(e) => setQ({ ...q, options: e.target.value.split("\n") })} placeholder="Варианты ответов, каждый с новой строки" />}{q.type === "multi_choice" && <input className="field max-w-xs" type="number" value={q.maxChoices ?? 3} onChange={(e) => setQ({ ...q, maxChoices: Number(e.target.value) || 3 })} placeholder="Максимум вариантов" />}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={q.required} onChange={(e) => setQ({ ...q, required: e.target.checked })} /> Обязательный вопрос</label><div className="flex gap-2"><button className="button-secondary" onClick={() => void saveQuestion(q, create)}>{create ? "Добавить вопрос" : "Сохранить"}</button>{!create && <button className="button-secondary text-red-700" onClick={() => void remove(q.id)}>Удалить</button>}</div></div>; }
  return <section className="space-y-5"><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Добавить вопрос</h3><p className="mt-1 text-sm text-zinc-500">Ветка определяет, кому показывать вопрос: всем, только магазину, офису или складу.</p><div className="mt-4">{renderForm(draft, setDraft, true)}</div>{message && <p className="mt-3 text-sm text-emerald-700">{message}</p>}</div><div className="space-y-3">{questions.map((q) => <QuestionRow key={q.id} q={q} renderForm={renderForm} />)}</div></section>;
}
function QuestionRow({ q, renderForm }: { q: Question; renderForm: any }) { const [open, setOpen] = useState(false); const [local, setLocal] = useState(q); useEffect(() => setLocal(q), [q]); return <div className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm"><button className="flex w-full items-start justify-between gap-4 text-left" onClick={() => setOpen(!open)}><span><b>{q.position}. {q.text}</b><span className="mt-1 block text-xs text-zinc-500">{TYPE_LABELS[q.type]} · {LABELS[q.category] ?? q.category} · {BRANCHES.find((b) => b.value === branchOf(q.code))?.label}</span></span><span className="text-sm text-zinc-400">{open ? "Свернуть" : "Редактировать"}</span></button>{open && <div className="mt-4">{renderForm(local, setLocal, false)}</div>}</div>; }

export function HrSurveysPanel() {
  const [data, setData] = useState<SurveyData>({ surveys: [], activeSurvey: null, analytics: null, campaigns: [] });
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [view, setView] = useState<View>("overview");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string>("");
  const [newTitle, setNewTitle] = useState("Новый HR-опрос");

  const load = useCallback(async (surveyId = selectedId) => {
    setLoading(true); setError("");
    try {
      const url = surveyId ? `/api/admin/surveys?surveyId=${encodeURIComponent(surveyId)}` : "/api/admin/surveys";
      const next = await api<SurveyData>(url);
      setData(next);
      setSelectedId(next.selectedSurveyId ?? surveyId ?? next.activeSurvey?.id ?? next.surveys[0]?.id ?? "");
    } catch (e) { setError(e instanceof Error ? e.message : "Не удалось загрузить опросы"); }
    finally { setLoading(false); }
  }, [selectedId]);
  useEffect(() => { void load(""); }, []);

  async function action(actionName: string, id?: string, extra: any = {}) {
    const result = await api<any>("/api/admin/surveys", { method: "POST", body: JSON.stringify({ action: actionName, id, ...extra }) });
    await load(result.id ?? id ?? selectedId);
    return result;
  }
  async function sendInvite() {
    if (!activeSurvey) return;
    const count = data.diagnostics?.knownBotUsers ?? 0;
    if (count <= 0) { setError("Пока нет пользователей бота для рассылки. Сотрудники должны хотя бы один раз открыть бота или написать ему."); return; }
    if (!confirm(`Отправить приглашение пройти опрос ${count} пользователям бота?`)) return;
    setSending(true); setError(""); setNotice("");
    try {
      const result = await action("survey.send", activeSurvey.id, { confirm: "SEND_SURVEY" });
      setNotice(`Приглашение отправлено: ${result.sent} из ${result.total}. Ошибок: ${result.failed}.`);
    } catch (e) { setError(e instanceof Error ? e.message : "Не удалось отправить приглашение"); }
    finally { setSending(false); }
  }

  const activeSurvey = useMemo(() => data.surveys.find((survey) => survey.id === selectedId) ?? data.surveys.find((survey) => survey.id === data.activeSurvey?.id) ?? data.surveys[0] ?? null, [data, selectedId]);
  const a = data.analytics;
  const categories = [...(a?.categories ?? [])].sort((x, y) => x.average - y.average);
  const problems = [...(a?.problems ?? [])].sort((x, y) => y.count - x.count);
  const redCount = categories.filter((c) => c.zone === "red").length;
  const yellowCount = categories.filter((c) => c.zone === "yellow").length;
  const normalCount = categories.filter((c) => c.zone === "normal").length;
  const actions = a?.actionPlan?.length ? a.actionPlan : [];
  const comments = (a?.comments ?? []).filter((c) => !query.trim() || `${c.answer} ${c.question} ${c.topic ?? ""} ${c.employeeGroup ?? ""} ${c.employeeRole ?? ""}`.toLowerCase().includes(query.trim().toLowerCase()));
  const tabs: Array<[View, string]> = [["overview", "Обзор"], ["actions", "План действий"], ["problems", "Проблемы"], ["slices", "Срезы"], ["comments", "Комментарии"], ["questions", "Вопросы"], ["surveys", "Опросы"]];

  return <div className="space-y-8">
    <div className="overflow-hidden rounded-[2rem] border border-zinc-200 bg-zinc-950 p-6 text-white shadow-sm"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">HR dashboard</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Опросы сотрудников</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-300">Создавайте опросы, редактируйте вопросы, запускайте рассылку в MAX и смотрите отчёт по каждому запуску отдельно.</p></div><div className="flex flex-wrap gap-2"><button className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-zinc-950 hover:bg-zinc-100" onClick={() => void action("survey.ensureDefault")}>Обновить базовый шаблон</button>{activeSurvey && <button className="rounded-xl bg-emerald-400 px-4 py-2 text-sm font-medium text-zinc-950 hover:bg-emerald-300 disabled:opacity-60" onClick={() => void sendInvite()} disabled={sending}>{sending ? "Отправляю..." : "Отправить приглашение"}</button>}{activeSurvey && <a className="rounded-xl border border-white/20 px-4 py-2 text-sm font-medium text-white hover:bg-white/10" href={`/api/admin/surveys/export?surveyId=${encodeURIComponent(activeSurvey.id)}`}>Скачать Excel</a>}</div></div>{data.diagnostics && <div className="mt-6 flex flex-wrap gap-2"><StatusPill ok={data.diagnostics.defaultSurveyCreated} label="базовый шаблон есть" /><StatusPill ok={Boolean(data.diagnostics.activeSurveyId)} label="текущий опрос выбран" /><StatusPill ok={data.diagnostics.surveyHashSaltConfigured} label="анонимизация" /><StatusPill ok={(data.diagnostics.knownBotUsers ?? 0) > 0} label={`${data.diagnostics.knownBotUsers ?? 0} пользователей бота`} /></div>}</div>
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
    {notice && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</div>}

    <div className="rounded-[2rem] border border-zinc-200 bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]"><select className="field text-base" value={selectedId} onChange={(e) => { setSelectedId(e.target.value); void load(e.target.value); }}>{data.surveys.map((survey) => <option key={survey.id} value={survey.id}>{cleanTitle(survey.title)} · {statusLabel(survey.status)} · {survey.stats.completed} ответов</option>)}</select>{activeSurvey && <button className="button-secondary" onClick={() => void action("survey.activate", activeSurvey.id)}>{activeSurvey.status === "active" ? "Уже текущий" : "Сделать текущим"}</button>}{activeSurvey && <button className="button-secondary" onClick={() => void action("survey.duplicate", activeSurvey.id)}>Новый запуск на основе этого</button>}{activeSurvey && <button className="button-secondary" onClick={() => setView("questions")}>Настроить вопросы</button>}</div>{activeSurvey && <div className="mt-4 flex flex-wrap items-center gap-2 text-sm"><Pill className={statusClass(activeSurvey.status)}>{statusLabel(activeSurvey.status)}</Pill><span className="text-zinc-500">{cleanTitle(activeSurvey.title)}</span><span className="text-zinc-300">•</span><span className="text-zinc-500">вопросов: {activeSurvey.questionCount}</span><span className="text-zinc-300">•</span><span className="text-zinc-500">завершено: {activeSurvey.stats.completed}</span></div>}</div>
    <div className="flex gap-2 overflow-x-auto rounded-2xl border border-zinc-200 bg-white p-2 shadow-sm">{tabs.map(([id, label]) => <button className={`min-w-max rounded-xl px-4 py-2 text-sm font-medium ${view === id ? "bg-zinc-950 text-white" : "text-zinc-600 hover:bg-zinc-100"}`} key={id} onClick={() => setView(id)}>{label}</button>)}</div>

    {view === "overview" && <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi title="Завершено" value={a?.completed ?? 0} hint={`${a?.completionRate ?? 0}% дошли до конца`} zone={(a?.completionRate ?? 0) >= 70 ? "normal" : (a?.completionRate ?? 0) >= 40 ? "yellow" : "red"} /><Kpi title="Средний балл" value={a?.scaleAverage ?? "—"} hint="Только завершённые анкеты" zone={scoreZone(a?.scaleAverage ?? null)} /><Kpi title="Индекс риска" value={a?.riskIndex ?? "—"} hint="0-100, чем выше, тем хуже" zone={riskZone(a?.riskIndex)} /><Kpi title="eNPS" value={a?.enps?.score ?? "—"} hint={`${a?.enps?.responses ?? 0} ответов`} zone={(a?.enps?.score ?? 0) < 0 ? "red" : (a?.enps?.score ?? 0) < 30 ? "yellow" : "normal"} /></section><section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Карта риска</h3><div className="mt-6"><RiskDonut red={redCount} yellow={yellowCount} normal={normalCount} /></div></div><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Слабые категории</h3><div className="mt-5"><BarRows items={categories.slice(0, 8)} type="category" /></div></div></section><section className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Последние рассылки</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{(data.campaigns ?? []).map((campaign) => <div className="rounded-2xl border border-zinc-200 p-4" key={campaign.id}><div className="flex items-center justify-between gap-3"><p className="font-semibold">{campaignStatus(campaign.status)}</p><Pill className={campaign.failed ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}>{campaign.sent}/{campaign.total}</Pill></div><p className="mt-2 text-sm text-zinc-500">Ошибок: {campaign.failed} · {campaign.finishedAt ? new Date(campaign.finishedAt).toLocaleString("ru-RU") : "в процессе"}</p></div>)}{!(data.campaigns ?? []).length && <p className="rounded-2xl bg-zinc-50 p-5 text-sm text-zinc-500">Рассылок по этому опросу ещё не было.</p>}</div></section></>}
    {view === "actions" && <section className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">План действий HR</h3><div className="mt-5 grid gap-3">{actions.map((item) => <div className={`rounded-2xl border p-4 ${zoneClass(item.zone)}`} key={item.id}><div className="flex items-center justify-between gap-3"><p className="font-semibold">{item.priority} · {item.title}</p><span className="rounded-full bg-white/70 px-3 py-1 text-xs font-semibold">{item.metric}</span></div><p className="mt-2 text-sm leading-6">{item.action}</p></div>)}{!actions.length && <p className="rounded-2xl bg-zinc-50 p-5 text-sm text-zinc-500">Пока нет красных или жёлтых зон.</p>}</div></section>}
    {view === "problems" && <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Проблемы</h3><div className="mt-5"><BarRows items={problems} type="problem" /></div></div><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Категории</h3><div className="mt-5"><BarRows items={categories} type="category" /></div></div></section>}
    {view === "slices" && <section className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Срезы</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{(a?.slices ?? []).map((item) => <div className="rounded-2xl border border-zinc-200 p-4" key={`${item.slice}-${item.group}`}><div className="flex items-center justify-between gap-3"><p className="font-semibold">{item.slice}: {item.group}</p><span className={`rounded-full px-3 py-1 text-xs font-semibold ${zoneClass(item.zone)}`}>{item.average ?? "—"}</span></div><p className="mt-2 text-sm text-zinc-500">Анкет: {item.count} · {reliabilityText(item.reliability)} · топ проблема: {item.topProblem ?? "нет"}</p></div>)}</div></section>}
    {view === "comments" && <section className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h3 className="text-xl font-semibold">Комментарии HR</h3><p className="mt-1 text-sm text-zinc-500">Открытые ответы. Поиск по теме, роли, группе или тексту.</p></div><input className="field max-w-sm" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск" /></div><div className="mt-5 space-y-3">{comments.slice(0, 60).map((comment) => <blockquote className={`rounded-2xl border p-4 text-sm leading-6 ${comment.urgency === "critical" ? zoneClass("red") : comment.urgency === "attention" ? zoneClass("yellow") : "border-zinc-200 bg-zinc-50"}`} key={`${comment.sessionAnonId}-${comment.question}-${comment.answer}`}><p>“{comment.answer}”</p><footer className="mt-2 text-xs opacity-70">{comment.topic ?? "Другое"} · {comment.question}</footer></blockquote>)}</div></section>}
    {view === "questions" && activeSurvey && <QuestionEditor surveyId={activeSurvey.id} />}
    {view === "surveys" && <section className="space-y-5"><div className="rounded-[2rem] border border-zinc-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold">Создать новый опрос</h3><p className="mt-1 text-sm text-zinc-500">Для нового месяца или отдельного отдела лучше делать новый опрос, чтобы ответы и Excel не смешивались.</p><div className="mt-4 flex gap-2"><input className="field" value={newTitle} onChange={(e) => setNewTitle(e.target.value)} /><button className="button-secondary" onClick={() => void action("survey.create", undefined, { title: newTitle, description: "" })}>Создать</button></div></div>{activeSurvey && <div className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-6 shadow-sm"><h3 className="text-xl font-semibold text-emerald-950">Запуск опроса</h3><p className="mt-1 text-sm text-emerald-800">Нажмите кнопку, и бот отправит приглашение всем сотрудникам, которые уже открывали бота. Получателей сейчас: {data.diagnostics?.knownBotUsers ?? 0}.</p><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-60" onClick={() => void sendInvite()} disabled={sending}>{sending ? "Отправляю..." : "Отправить приглашение в MAX"}</button><button className="button-secondary" onClick={() => void action("survey.activate", activeSurvey.id)}>Сделать текущим без рассылки</button></div></div>}<div className="grid gap-4">{data.surveys.map((survey) => <article className="rounded-2xl border border-zinc-200 bg-white p-4" key={survey.id}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{cleanTitle(survey.title)}</p><Pill className={statusClass(survey.status)}>{statusLabel(survey.status)}</Pill></div><p className="mt-1 text-sm text-zinc-500">Вопросов: {survey.questionCount} · начато: {survey.stats.started} · завершено: {survey.stats.completed}</p></div><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={() => { setSelectedId(survey.id); void load(survey.id); }}>Открыть</button><a className="button-secondary" href={`/api/admin/surveys/export?surveyId=${encodeURIComponent(survey.id)}`}>Excel</a><button className="button-secondary" onClick={() => void action("survey.duplicate", survey.id)}>Новый запуск</button><button className="button-secondary" onClick={() => void action("survey.activate", survey.id)}>{survey.status === "active" ? "Текущий" : "Сделать текущим"}</button><button className="button-secondary text-red-700" onClick={() => { if (confirm("Удалить опрос вместе с ответами?")) void action("survey.delete", survey.id); }}>Удалить</button></div></div></article>)}</div></section>}
  </div>;
}
