import type { HrSurveyQuestion } from "./types";
export const DEFAULT_HR_SURVEY_ID = "superceny-employee-satisfaction";
export const DEFAULT_HR_SURVEY = { id: DEFAULT_HR_SURVEY_ID, title: "Удовлетворенность сотрудников Суперцены", description: "Опрос анонимный. Мы не собираем ФИО. Цель опроса - понять, что мешает работать нормально, что нужно улучшить в магазинах и офисе, и какие проблемы повторяются чаще всего. Отвечайте честно, это поможет сделать работу удобнее." };
type Q = Omit<HrSurveyQuestion,"id"|"surveyId">;
const scale = (position:number, text:string, category:string): Q => ({ position, code:`q${position}`, text, category, type:"scale_1_5", options:[], required:true, maxChoices:null });
export const DEFAULT_HR_QUESTIONS: Q[] = [
{position:1,code:"workplace",text:"Где вы работаете?",category:"profile",type:"single_choice",options:["Магазин","Офис","Склад","Другое"],required:true,maxChoices:null},
{position:2,code:"role",text:"Ваша роль?",category:"profile",type:"single_choice",options:["Продавец-кассир","Старший смены","Администратор","Товаровед","Офисный сотрудник","Руководитель","Другое"],required:true,maxChoices:null},
{position:3,code:"tenure",text:"Как давно вы работаете в Суперценах?",category:"profile",type:"single_choice",options:["Меньше 1 месяца","1-3 месяца","3-6 месяцев","6-12 месяцев","Больше года"],required:true,maxChoices:null},
{position:4,code:"store_or_department",text:"Укажите магазин или отдел, если готовы. Если не хотите указывать, напишите «не указывать».",category:"profile",type:"text",options:[],required:false,maxChoices:null},
scale(5,"Я понимаю, что от меня ожидают на работе.","clarity"),scale(6,"Мне понятно, какие задачи важнее всего в течение смены или рабочего дня.","clarity"),scale(7,"У меня есть всё необходимое для нормальной работы.","working_conditions"),scale(8,"Рабочая нагрузка в моей смене или в течение дня адекватная.","workload"),scale(9,"График работы составляется понятно и заранее.","schedule"),scale(10,"Мне хватает времени, чтобы выполнять работу качественно.","workload"),scale(11,"В коллективе нормальная рабочая атмосфера.","team"),scale(12,"В моей команде сотрудники помогают друг другу.","team"),scale(13,"Руководитель общается со мной уважительно.","manager"),scale(14,"Руководитель помогает решать рабочие вопросы, а не только требует результат.","manager"),scale(15,"Я могу спокойно задать вопрос руководителю, если что-то непонятно.","manager"),scale(16,"Я получаю понятную обратную связь по своей работе.","manager"),scale(17,"Обучения хватает, чтобы нормально выполнять мои задачи.","training"),scale(18,"Когда я только начинал работать, мне нормально объяснили обязанности.","onboarding"),scale(19,"Правила, инструкции и требования в компании понятные.","rules"),scale(20,"Изменения в работе до меня доводят вовремя.","communication"),scale(21,"Зарплата, премии и штрафы мне понятны.","compensation"),scale(22,"Я считаю оплату труда справедливой относительно нагрузки.","compensation"),scale(23,"Я вижу, что хорошую работу в компании замечают.","recognition"),scale(24,"Я вижу для себя возможность развиваться в компании.","growth"),scale(25,"Я чувствую, что компания относится к сотрудникам по-человечески.","trust"),scale(26,"Насколько вы сейчас довольны работой в Суперценах?","satisfaction"),
{position:27,code:"enps",text:"Готовы ли вы рекомендовать работу в Суперценах знакомым?",category:"enps",type:"single_choice",options:["Нет","Скорее нет","Не знаю","Скорее да","Да"],required:true,maxChoices:null},
{position:28,code:"blockers",text:"Что сейчас больше всего мешает вам работать нормально? Можно выбрать до 3 вариантов. Напишите номера через запятую.",category:"blockers",type:"multi_choice",options:["Нехватка сотрудников","Большая нагрузка","График","Зарплата","Руководитель","Коллектив","Нехватка обучения","Нехватка оборудования или расходников","Плохая коммуникация","Непонятные задачи","Другое"],required:true,maxChoices:3},
{position:29,code:"improvements",text:"Что в первую очередь нужно улучшить? Можно выбрать до 3 вариантов. Напишите номера через запятую.",category:"improvements",type:"multi_choice",options:["Графики","Обучение","Зарплату и премии","Коммуникацию с руководителем","Условия на рабочем месте","Количество сотрудников в смене","Понятность задач","Адаптацию новичков","Работу офиса с магазинами","Атмосферу в коллективе","Другое"],required:true,maxChoices:3},
{position:30,code:"one_change",text:"Какое одно изменение сильнее всего улучшило бы вашу работу?",category:"comment",type:"text",options:[],required:true,maxChoices:null},
{position:31,code:"keep_good",text:"Что в компании уже работает хорошо и это важно сохранить?",category:"comment",type:"text",options:[],required:false,maxChoices:null},
{position:32,code:"anonymous_problem",text:"Есть ли проблема, о которой вы хотите сообщить анонимно?",category:"anonymous_problem",type:"text",options:[],required:false,maxChoices:null}
];
